### ISSUE TITLE
The app seems to be missing from the App Store.

### ISSUE THREAD

**Issue by kallipigous** [nthState/GestureKit#6]
I can't seem to find the gesture app. Is there a TestFlight version?

**Comment by nthState-Chris** [comment]
Hi @kallipigous , I'm waiting for Apple to give me a thumbs-up on the review, it's taking longer than expected.

**Comment by nthState-Chris** [comment]
Hi, sorry for the delay, the App is still In-Review with Apple.

**Comment by nthState-Chris** [comment]
GestureComposer was released on July 2nd 2024, you can download it here: https://apps.apple.com/us/app/gesture-composer/id6478170862
